[zh-cn]
  LanguageName = "简体中文"
  weight = 1
  contentDir = "content/zh-cn"

[zh-tw]
  LanguageName = "繁體中文"
  weight = 2
  contentDir = "content/zh-tw"

[en]
  LanguageName = "English"
  weight = 3
  contentDir = "content/en"
