[[main]]
  name = "分类"
  identifier = "categories"
  weight = 20
  url = "categories"
  pre = '<i class="fas fa-fw fa-folder"></i>'
[[main]]
  parent = "categories"
  name = "Programing"
  url = "categories/programing"
  pre = '<i class="fas fa-fw fa-code"></i>'
  weight = 1
[[main]]
  parent = "categories"
  name = "Linux"
  url = "categories/linux"
  pre = '<i class="fab fa-fw fa-linux"></i>'
  weight = 2
[[main]]
  parent = "categories"
  name = "Server"
  url = "categories/server"
  pre = '<i class="fas fa-fw fa-server"></i>'
  weight = 3
[[main]]
  parent = "categories"
  name = "所有分类"
  url = "categories"
  pre = '<i class="fas fa-fw fa-folder"></i>'
  weight = 100

[[main]]
  name = "标签"
  identifier = "tags"
  weight = 30
  url = "tags"
  pre = '<i class="fas fa-fw fa-tags"></i>'
[[main]]
  parent = "tags"
  name = "PHP"
  url = "tags/php"
  pre = '<i class="fab fa-fw fa-php"></i>'
  weight = 1
[[main]]
  parent = "tags"
  name = "Go"
  url = "tags/go"
  pre = '<i class="fab fa-fw fa-google"></i>'
  weight = 2
[[main]]
  parent = "tags"
  name = "MySQL"
  url = "tags/mysql"
  pre = '<i class="fas fa-fw fa-database"></i>'
  weight = 3
[[main]]
  parent = "tags"
  name = "HTML"
  url = "tags/html"
  pre = '<i class="fab fa-fw fa-html5"></i>'
  weight = 4
[[main]]
  parent = "tags"
  name = "JavaScript"
  url = "tags/mysql"
  pre = '<i class="fab fa-fw fa-js"></i>'
  weight = 5
[[main]]
  parent = "tags"
  name = "CSS"
  url = "tags/css"
  pre = '<i class="fab fa-fw fa-css3"></i>'
  weight = 6
[[main]]
  parent = "tags"
  name = "所有标签"
  url = "tags"
  pre = '<i class="fas fa-fw fa-tags"></i>'
  weight = 100

[[main]]
  name = "专栏"
  identifier = "series"
  weight = 40
  url = "series"
  pre = '<i class="fas fa-fw fa-columns"></i>'

[[main]]
  name = "项目"
  identifier = "projects"
  weight = 100

[[main]]
  parent = "projects"
  name = "CleverGo"
  url = "https://clevergo.tech/"
[[main]]
  parent = "projects"
  name = "GOPKGS"
  url = "https://gopkgs.net/"
[[main]]
  parent = "projects"
  name = "Yii 2 管理后台"
  url = "https://admin.yii2.razonyang.com/"
[[main]]
  parent = "projects"
  name = "Hugo Bootstrap 主题"
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
